### ISSUE TITLE
Option to overwrite the signatures

### ISSUE THREAD

**Issue by azmeuk** [mansenfranzen/autodoc_pydantic#288]
Thanks to #285 I can remove the signature prefix from the fields. This makes it less confusing for users who do want to use and parameter my application, but does not care about python things. However I would love to go further by totally removing the signature of the class, and replace it by something more useful to end-users, like where to write the expected settings in the configuration file.

![Capture d’écran du 2024-05-17 22-46-22](https://github.com/mansenfranzen/autodoc_pydantic/assets/60163/0a596ab4-d37e-4d2c-8dbe-1752d50c6b21)

For instance, here I would love to be able to replace `canaille.core.configuration.SMTPSettings` by `CANAILLE.SMTP` because this is where users have to write their SMTP configuration.

```toml
[CANAILLE.SMTP]
HOST = "localhost"
PORT = 25
TLS = false
SSL = false
LOGIN = ""
PASSWORD = ""
FROM_ADDR = "admin@mydomain.tld"
```

In addition, that would make the TOC much more useful for end-users if the new signature was referenced there instead of the class path.

What do you think?
